In [2]:
import cv2
import numpy as np
from ultralytics import YOLO

In [12]:
# Load the YOLO8v8 model
model = YOLO("yolov8n.pt")

In [15]:
# # 동영상 파일 사용시
video_path = "data/soccer.mp4"
cap = cv2.VideoCapture(video_path)

In [25]:
# # webcam 사용시
# cap = cv2.VideoCapture(0)

In [16]:
# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 inference on the frame
        results = model(frame, classes=0)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Inference", annotated_frame)

        conf = results[0].boxes.conf
        print(conf)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()


0: 640x384 3 persons, 116.0ms
Speed: 2.0ms preprocess, 116.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 78.0ms
Speed: 2.0ms preprocess, 78.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9147, 0.7093, 0.2857])
tensor([0.9210, 0.7036, 0.2676])


0: 640x384 2 persons, 85.0ms
Speed: 3.0ms preprocess, 85.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 84.0ms
Speed: 3.0ms preprocess, 84.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 79.0ms


tensor([0.9244, 0.6313])
tensor([0.9309, 0.3713])


Speed: 2.0ms preprocess, 79.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 74.0ms
Speed: 2.0ms preprocess, 74.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 77.0ms
Speed: 1.0ms preprocess, 77.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9297, 0.3224])
tensor([0.9307, 0.2952])
tensor([0.9335, 0.3567])


0: 640x384 1 person, 78.0ms
Speed: 4.0ms preprocess, 78.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 79.0ms
Speed: 1.0ms preprocess, 79.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 72.0ms
Speed: 2.0ms preprocess, 72.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.9351])
tensor([0.9330])
tensor([0.9270])



0: 640x384 1 person, 76.0ms
Speed: 2.0ms preprocess, 76.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 78.0ms
Speed: 2.0ms preprocess, 78.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 80.0ms


tensor([0.9249])
tensor([0.9268])


Speed: 3.0ms preprocess, 80.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 102.0ms
Speed: 2.0ms preprocess, 102.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 69.0ms


tensor([0.9316])
tensor([0.9324])


Speed: 2.0ms preprocess, 69.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 76.0ms
Speed: 2.0ms preprocess, 76.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9336])
tensor([0.9322])
tensor([0.9348])


0: 640x384 1 person, 75.4ms
Speed: 3.0ms preprocess, 75.4ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 75.0ms
Speed: 2.0ms preprocess, 75.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 73.7ms


tensor([0.9344])
tensor([0.9359])


Speed: 2.0ms preprocess, 73.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 73.0ms
Speed: 1.0ms preprocess, 73.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 71.0ms
Speed: 2.0ms preprocess, 71.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9375])
tensor([0.9382])
tensor([0.9376])


0: 640x384 1 person, 77.0ms
Speed: 2.0ms preprocess, 77.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.9372])



0: 640x384 1 person, 106.0ms
Speed: 2.0ms preprocess, 106.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 88.7ms
Speed: 3.0ms preprocess, 88.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9375])
tensor([0.9387])


0: 640x384 1 person, 91.0ms
Speed: 3.0ms preprocess, 91.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 101.0ms
Speed: 6.0ms preprocess, 101.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9374])
tensor([0.9360, 0.2743])


0: 640x384 2 persons, 108.0ms
Speed: 6.0ms preprocess, 108.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 80.0ms
Speed: 2.0ms preprocess, 80.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 83.0ms


tensor([0.9348, 0.2552])
tensor([0.9300])


Speed: 2.0ms preprocess, 83.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 86.0ms
Speed: 3.0ms preprocess, 86.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9251])
tensor([0.9089])


0: 640x384 2 persons, 81.0ms
Speed: 1.0ms preprocess, 81.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 84.7ms
Speed: 2.0ms preprocess, 84.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 74.0ms


tensor([0.9063, 0.4127])
tensor([0.9345, 0.3014])


Speed: 3.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 89.0ms
Speed: 3.0ms preprocess, 89.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 71.0ms
Speed: 2.0ms preprocess, 71.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.9316, 0.5806, 0.3187])
tensor([0.9106, 0.7057])
tensor([0.8964, 0.8204])



0: 640x384 3 persons, 78.0ms
Speed: 2.0ms preprocess, 78.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 71.0ms
Speed: 3.0ms preprocess, 71.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 73.0ms
Speed: 1.0ms preprocess, 73.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8872, 0.7419, 0.2847])
tensor([0.9173, 0.5832, 0.4896, 0.3371])
tensor([0.9378, 0.5201, 0.4604, 0.2789])


0: 640x384 2 persons, 77.0ms
Speed: 3.0ms preprocess, 77.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 75.0ms
Speed: 1.0ms preprocess, 75.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 69.0ms
Speed: 3.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9393, 0.7130])
tensor([0.9413, 0.7502])
tensor([0.9428, 0.7842, 0.3455])


0: 640x384 2 persons, 92.0ms
Speed: 2.0ms preprocess, 92.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 76.0ms
Speed: 2.0ms preprocess, 76.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 80.0ms


tensor([0.9299, 0.7728])
tensor([0.9401, 0.6946, 0.3759])


Speed: 3.0ms preprocess, 80.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 83.0ms
Speed: 2.0ms preprocess, 83.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 80.0ms


tensor([0.9322, 0.6831])
tensor([0.9147, 0.5522])


Speed: 2.0ms preprocess, 80.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 82.0ms
Speed: 2.0ms preprocess, 82.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 74.0ms


tensor([0.9206, 0.8546])
tensor([0.8983, 0.7768, 0.2685])


Speed: 2.0ms preprocess, 74.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 78.0ms
Speed: 2.0ms preprocess, 78.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 76.0ms


tensor([0.8706, 0.7005])
tensor([0.8809, 0.7551])


Speed: 1.0ms preprocess, 76.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 79.0ms
Speed: 1.0ms preprocess, 79.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 73.0ms


tensor([0.9048, 0.5819])
tensor([0.8993, 0.7018])


Speed: 2.0ms preprocess, 73.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 81.0ms
Speed: 2.0ms preprocess, 81.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 76.0ms


tensor([0.8979, 0.8296])
tensor([0.9161, 0.7972])


Speed: 2.0ms preprocess, 76.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 94.4ms
Speed: 2.0ms preprocess, 94.4ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9224, 0.8298])
tensor([0.9095, 0.8319])


0: 640x384 3 persons, 69.0ms
Speed: 1.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 74.7ms
Speed: 3.0ms preprocess, 74.7ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 71.5ms
Speed: 2.0ms preprocess, 71.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8132, 0.7579, 0.2537])
tensor([0.8083, 0.5728, 0.2708])
tensor([0.8454, 0.7192, 0.3647, 0.3278, 0.2526])


0: 640x384 5 persons, 73.0ms
Speed: 2.0ms preprocess, 73.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 78.0ms
Speed: 2.0ms preprocess, 78.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 71.0ms


tensor([0.8410, 0.6125, 0.4131, 0.3708, 0.3334])
tensor([0.7979, 0.6519, 0.3470, 0.2549])


Speed: 2.0ms preprocess, 71.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 78.0ms
Speed: 2.0ms preprocess, 78.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 73.0ms
Speed: 2.0ms preprocess, 73.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.7928, 0.7819, 0.4618, 0.4146, 0.4143])
tensor([0.8817, 0.7190, 0.5391])
tensor([0.7736, 0.5721, 0.5669, 0.4214])



0: 640x384 4 persons, 76.0ms
Speed: 2.0ms preprocess, 76.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 73.0ms
Speed: 3.0ms preprocess, 73.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 74.0ms


tensor([0.7450, 0.6302, 0.3965, 0.2917])
tensor([0.7738, 0.5634, 0.2885, 0.2786, 0.2513])


Speed: 2.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 78.0ms
Speed: 2.0ms preprocess, 78.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 74.0ms


tensor([0.8117, 0.6234, 0.2602])
tensor([0.7883, 0.6346, 0.4320])


Speed: 2.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 95.0ms
Speed: 2.0ms preprocess, 95.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 72.0ms


tensor([0.8487, 0.6164, 0.5488])
tensor([0.8819, 0.6483, 0.4101, 0.3691])


Speed: 2.0ms preprocess, 72.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 73.0ms
Speed: 2.0ms preprocess, 73.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 73.7ms
Speed: 4.0ms preprocess, 73.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8706, 0.5888, 0.5644])
tensor([0.9137, 0.5163, 0.4613, 0.3107])
tensor([0.8936, 0.6736, 0.5409, 0.3167])


0: 640x384 3 persons, 75.0ms
Speed: 2.0ms preprocess, 75.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 86.7ms
Speed: 2.0ms preprocess, 86.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 76.0ms


tensor([0.6943, 0.6824, 0.6218])
tensor([0.8593, 0.8262, 0.5889])


Speed: 2.0ms preprocess, 76.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 76.0ms
Speed: 4.0ms preprocess, 76.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 74.0ms


tensor([0.8876, 0.8876, 0.5268])
tensor([0.9068, 0.8875, 0.4320])


Speed: 3.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 77.3ms
Speed: 2.0ms preprocess, 77.3ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 70.0ms


tensor([0.9353, 0.8739, 0.5745])
tensor([0.9289, 0.8998, 0.5436])


Speed: 2.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 80.0ms
Speed: 2.0ms preprocess, 80.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 77.0ms


tensor([0.9154, 0.8845, 0.5147])
tensor([0.9001, 0.8899, 0.5377])


Speed: 2.0ms preprocess, 77.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 83.8ms
Speed: 2.0ms preprocess, 83.8ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9080, 0.9034, 0.5925])
tensor([0.9223, 0.8933, 0.6478])


0: 640x384 3 persons, 84.0ms
Speed: 15.0ms preprocess, 84.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 89.7ms
Speed: 2.0ms preprocess, 89.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9213, 0.8993, 0.5094])
tensor([0.9028, 0.8987, 0.4275])


0: 640x384 2 persons, 82.0ms
Speed: 3.0ms preprocess, 82.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 74.4ms
Speed: 2.0ms preprocess, 74.4ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 70.0ms
Speed: 2.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9102, 0.9032])
tensor([0.9089, 0.8942, 0.4223])
tensor([0.9051, 0.9006, 0.4686])


0: 640x384 3 persons, 78.0ms
Speed: 2.0ms preprocess, 78.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 80.0ms
Speed: 1.0ms preprocess, 80.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 70.7ms
Speed: 3.0ms preprocess, 70.7ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9060, 0.8950, 0.4151])
tensor([0.9215, 0.9137, 0.4581])
tensor([0.9209, 0.9070, 0.7921])


0: 640x384 4 persons, 75.0ms
Speed: 2.0ms preprocess, 75.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 70.0ms
Speed: 2.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 63.0ms
Speed: 2.0ms preprocess, 63.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.9266, 0.9169, 0.6273, 0.5739])
tensor([0.9345, 0.9045, 0.6124])
tensor([0.9417, 0.8988, 0.7450])



0: 640x384 3 persons, 72.0ms
Speed: 3.0ms preprocess, 72.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 77.0ms
Speed: 2.0ms preprocess, 77.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9431, 0.9038, 0.7858])
tensor([0.9397, 0.8910, 0.7275])


0: 640x384 3 persons, 93.0ms
Speed: 8.0ms preprocess, 93.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 82.0ms
Speed: 3.0ms preprocess, 82.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 65.0ms


tensor([0.9349, 0.9052, 0.7927])
tensor([0.9523, 0.9076, 0.8256])


Speed: 2.0ms preprocess, 65.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 74.0ms
Speed: 2.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 62.4ms
Speed: 2.0ms preprocess, 62.4ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9186, 0.9139, 0.8374])
tensor([0.9229, 0.8983, 0.8005])
tensor([0.9222, 0.8890, 0.8206])


0: 640x384 3 persons, 68.0ms
Speed: 2.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 68.7ms
Speed: 2.0ms preprocess, 68.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 64.0ms
Speed: 2.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9246, 0.9146, 0.7826])
tensor([0.9213, 0.9152, 0.7836])
tensor([0.9116, 0.8884, 0.8041])


0: 640x384 3 persons, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 77.0ms
Speed: 2.0ms preprocess, 77.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 61.0ms
Speed: 2.0ms preprocess, 61.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9097, 0.8768, 0.8052])
tensor([0.9200, 0.8857, 0.7492])
tensor([0.8910, 0.8903, 0.6957])


0: 640x384 4 persons, 85.0ms
Speed: 2.0ms preprocess, 85.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 70.0ms
Speed: 2.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 65.0ms
Speed: 2.0ms preprocess, 65.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8937, 0.8902, 0.6472, 0.3232])
tensor([0.9146, 0.8377, 0.5565, 0.4880])
tensor([0.8946, 0.8707, 0.6616, 0.3538])


0: 640x384 3 persons, 65.7ms
Speed: 2.0ms preprocess, 65.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 64.0ms
Speed: 2.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9101, 0.8547, 0.7229])
tensor([0.8973, 0.8806, 0.8395])
tensor([0.9369, 0.8732, 0.8101])


0: 640x384 3 persons, 70.0ms
Speed: 2.0ms preprocess, 70.0ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 65.0ms
Speed: 3.0ms preprocess, 65.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 66.0ms
Speed: 2.0ms preprocess, 66.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9261, 0.9020, 0.7554])
tensor([0.9273, 0.8484, 0.8285])
tensor([0.9404, 0.8868, 0.8198])


0: 640x384 3 persons, 76.0ms
Speed: 3.0ms preprocess, 76.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 76.7ms
Speed: 2.0ms preprocess, 76.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 69.3ms


tensor([0.9423, 0.8857, 0.8668])
tensor([0.9286, 0.8730, 0.7906])


Speed: 2.0ms preprocess, 69.3ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 65.7ms
Speed: 2.0ms preprocess, 65.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9234, 0.8890, 0.5838])
tensor([0.9305, 0.8533, 0.5992])
tensor([0.9333, 0.8253, 0.6825])


0: 640x384 3 persons, 87.0ms
Speed: 2.0ms preprocess, 87.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 70.0ms
Speed: 3.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 69.0ms


tensor([0.9382, 0.8190, 0.8114])
tensor([0.9281, 0.8593, 0.8328])


Speed: 2.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 67.0ms
Speed: 3.0ms preprocess, 67.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 61.0ms
Speed: 2.0ms preprocess, 61.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9152, 0.8695, 0.8275])
tensor([0.9092, 0.8704, 0.7817, 0.3323])
tensor([0.8982, 0.8309, 0.8143])


0: 640x384 3 persons, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 74.0ms
Speed: 2.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 68.0ms


tensor([0.9028, 0.8428, 0.8412])
tensor([0.8591, 0.7447, 0.4801])


Speed: 2.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 68.0ms
Speed: 2.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 60.0ms
Speed: 1.0ms preprocess, 60.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9133, 0.6908])
tensor([0.9004, 0.6069])
tensor([0.8545, 0.2970])


0: 640x384 1 person, 71.0ms
Speed: 2.0ms preprocess, 71.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 69.7ms
Speed: 3.0ms preprocess, 69.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 64.0ms
Speed: 2.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9286])
tensor([0.9210, 0.3579])
tensor([0.9242])


0: 640x384 1 person, 67.0ms
Speed: 2.0ms preprocess, 67.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 90.0ms
Speed: 2.0ms preprocess, 90.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 64.0ms
Speed: 2.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9056])
tensor([0.9191, 0.3430])
tensor([0.9002, 0.4546])


0: 640x384 2 persons, 71.0ms
Speed: 3.0ms preprocess, 71.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 74.0ms
Speed: 4.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 62.0ms
Speed: 2.0ms preprocess, 62.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9032, 0.5655])
tensor([0.8940, 0.5486])
tensor([0.8483, 0.5348])


0: 640x384 1 person, 73.0ms
Speed: 3.0ms preprocess, 73.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 66.0ms
Speed: 2.0ms preprocess, 66.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8728])
tensor([0.8998])
tensor([0.8856])


0: 640x384 1 person, 67.0ms
Speed: 2.0ms preprocess, 67.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 70.0ms
Speed: 2.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 67.0ms
Speed: 2.0ms preprocess, 67.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.8876])
tensor([0.8886, 0.3901])



0: 640x384 2 persons, 68.0ms
Speed: 2.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 64.7ms
Speed: 2.0ms preprocess, 64.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8898, 0.5516])
tensor([0.9174, 0.5538])
tensor([0.9408, 0.5427])


0: 640x384 2 persons, 74.0ms
Speed: 3.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 99.0ms
Speed: 4.0ms preprocess, 99.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9372, 0.5204])
tensor([0.9423, 0.4773])


0: 640x384 2 persons, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 67.0ms
Speed: 2.0ms preprocess, 67.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 62.0ms
Speed: 2.0ms preprocess, 62.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.9286, 0.3267])
tensor([0.9185])
tensor([0.8445])



0: 640x384 1 person, 77.0ms
Speed: 2.0ms preprocess, 77.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 69.0ms
Speed: 3.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 68.0ms
Speed: 2.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8745])
tensor([0.8251, 0.5743])
tensor([0.7682, 0.5191])


0: 640x384 2 persons, 73.0ms
Speed: 2.0ms preprocess, 73.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 68.0ms
Speed: 2.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 65.0ms
Speed: 2.0ms preprocess, 65.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8276, 0.5803])
tensor([0.8223, 0.5945, 0.3669])
tensor([0.8099, 0.4452, 0.3793, 0.2938])


0: 640x384 2 persons, 67.4ms
Speed: 5.0ms preprocess, 67.4ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 72.0ms
Speed: 2.0ms preprocess, 72.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 65.0ms
Speed: 2.0ms preprocess, 65.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.7434, 0.5262])
tensor([0.8846, 0.4975, 0.2844])



0: 640x384 2 persons, 86.0ms
Speed: 2.0ms preprocess, 86.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 64.0ms


tensor([0.9072, 0.6495])
tensor([0.8989, 0.5361])


Speed: 1.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 67.0ms
Speed: 2.0ms preprocess, 67.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 64.0ms


tensor([0.8833])
tensor([0.8973])


Speed: 2.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 77.0ms
Speed: 2.0ms preprocess, 77.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 64.7ms
Speed: 2.0ms preprocess, 64.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.7988, 0.2526])
tensor([0.8232, 0.3411])
tensor([0.8718, 0.5110])


0: 640x384 1 person, 70.0ms
Speed: 2.0ms preprocess, 70.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 72.0ms
Speed: 2.0ms preprocess, 72.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 71.0ms
Speed: 3.0ms preprocess, 71.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8789])
tensor([0.9005])
tensor([0.9136])


0: 640x384 1 person, 69.0ms
Speed: 4.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 71.0ms
Speed: 3.0ms preprocess, 71.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 62.0ms
Speed: 2.0ms preprocess, 62.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8977])
tensor([0.8682])
tensor([0.8925])


0: 640x384 1 person, 66.5ms
Speed: 2.0ms preprocess, 66.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 71.0ms
Speed: 2.0ms preprocess, 71.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 64.0ms
Speed: 4.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.8973])
tensor([0.8926])
tensor([0.8778])



0: 640x384 1 person, 88.0ms
Speed: 2.0ms preprocess, 88.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 66.0ms
Speed: 2.0ms preprocess, 66.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 61.0ms
Speed: 2.0ms preprocess, 61.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.8127])
tensor([0.8628])
tensor([0.8037])



0: 640x384 1 person, 76.0ms
Speed: 2.0ms preprocess, 76.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 68.0ms
Speed: 3.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 70.0ms


tensor([0.8678])
tensor([0.7311])


Speed: 2.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 68.0ms
Speed: 1.0ms preprocess, 68.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 62.0ms
Speed: 2.0ms preprocess, 62.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8041])
tensor([0.7684])
tensor([0.7898])


0: 640x384 3 persons, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 70.0ms
Speed: 3.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 64.0ms
Speed: 2.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.7868, 0.5101, 0.3360])
tensor([0.8623, 0.6822])
tensor([0.9111, 0.7945])


0: 640x384 2 persons, 67.0ms
Speed: 2.0ms preprocess, 67.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 74.5ms
Speed: 3.0ms preprocess, 74.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9329, 0.8720])
tensor([0.9235, 0.8546])


0: 640x384 4 persons, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 109.9ms
Speed: 2.0ms preprocess, 109.9ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9097, 0.8472, 0.3706, 0.2549])
tensor([0.9168, 0.9117])


0: 640x384 2 persons, 71.0ms
Speed: 3.0ms preprocess, 71.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 73.0ms
Speed: 3.0ms preprocess, 73.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 61.0ms
Speed: 3.0ms preprocess, 61.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9072, 0.8921])
tensor([0.8980, 0.8842, 0.3466])
tensor([0.8835, 0.8650, 0.4716])


0: 640x384 3 persons, 72.0ms
Speed: 2.0ms preprocess, 72.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 74.6ms
Speed: 1.0ms preprocess, 74.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 67.0ms
Speed: 1.0ms preprocess, 67.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9061, 0.9053, 0.6484])
tensor([0.8702, 0.8661, 0.7332])
tensor([0.9171, 0.8580, 0.6463])


0: 640x384 3 persons, 72.0ms
Speed: 2.0ms preprocess, 72.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 67.0ms
Speed: 3.0ms preprocess, 67.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 66.0ms


tensor([0.9262, 0.7824, 0.7718])
tensor([0.8766, 0.8670, 0.7889])


Speed: 2.0ms preprocess, 66.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 77.0ms
Speed: 2.0ms preprocess, 77.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 70.0ms


tensor([0.8494, 0.8367, 0.8198])
tensor([0.8991, 0.8291, 0.7643])


Speed: 3.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 74.5ms
Speed: 2.0ms preprocess, 74.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 64.0ms


tensor([0.8762, 0.7983, 0.7589])
tensor([0.8413, 0.7161, 0.6294, 0.3480, 0.2511])


Speed: 3.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 84.0ms
Speed: 2.0ms preprocess, 84.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 66.0ms


tensor([0.8541, 0.7595, 0.4422, 0.3649, 0.2715])
tensor([0.8384, 0.7629, 0.4661, 0.2911])


Speed: 2.0ms preprocess, 66.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 70.0ms
Speed: 2.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 65.0ms
Speed: 2.0ms preprocess, 65.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8959, 0.6421, 0.5603, 0.2948])
tensor([0.9136, 0.6419, 0.5553])
tensor([0.8932, 0.6304, 0.3091, 0.3047])


0: 640x384 4 persons, 72.0ms
Speed: 2.0ms preprocess, 72.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 71.0ms
Speed: 2.0ms preprocess, 71.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 65.0ms
Speed: 3.0ms preprocess, 65.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8918, 0.8381, 0.3136, 0.2543])
tensor([0.8867, 0.7933, 0.5270, 0.4599, 0.3646])
tensor([0.8729, 0.8521, 0.2885])


0: 640x384 4 persons, 67.0ms
Speed: 2.0ms preprocess, 67.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 74.0ms
Speed: 2.0ms preprocess, 74.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 69.0ms
Speed: 4.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8772, 0.7193, 0.5520, 0.2567])
tensor([0.7489, 0.7127, 0.2961])
tensor([0.8467, 0.7667])


0: 640x384 2 persons, 73.0ms
Speed: 2.0ms preprocess, 73.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 67.0ms
Speed: 2.5ms preprocess, 67.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 59.0ms
Speed: 1.0ms preprocess, 59.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.7486, 0.7336])
tensor([0.8444, 0.7127])
tensor([0.8781, 0.6618])


0: 640x384 2 persons, 66.8ms
Speed: 2.0ms preprocess, 66.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 93.0ms
Speed: 2.0ms preprocess, 93.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9345, 0.8181])
tensor([0.9247, 0.8294])


0: 640x384 2 persons, 67.0ms
Speed: 1.0ms preprocess, 67.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 69.8ms
Speed: 2.0ms preprocess, 69.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 63.0ms
Speed: 2.0ms preprocess, 63.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9180, 0.7424])
tensor([0.9192, 0.7066])
tensor([0.9232, 0.6994])


0: 640x384 2 persons, 75.0ms
Speed: 2.0ms preprocess, 75.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 75.0ms
Speed: 3.0ms preprocess, 75.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9245, 0.6676])
tensor([0.9346, 0.4134])


0: 640x384 2 persons, 67.0ms
Speed: 2.0ms preprocess, 67.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 74.0ms
Speed: 2.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 65.0ms
Speed: 3.0ms preprocess, 65.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9357, 0.5868])
tensor([0.9262])
tensor([0.9061])


0: 640x384 1 person, 66.0ms
Speed: 2.0ms preprocess, 66.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 59.0ms
Speed: 2.0ms preprocess, 59.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9260])
tensor([0.9199])
tensor([0.9154])


0: 640x384 1 person, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 70.0ms
Speed: 3.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 64.7ms
Speed: 2.0ms preprocess, 64.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9131])
tensor([0.9006])
tensor([0.8899])


0: 640x384 1 person, 87.0ms
Speed: 2.0ms preprocess, 87.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 78.7ms
Speed: 2.0ms preprocess, 78.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 70.0ms


tensor([0.7356])
tensor([0.8600])


Speed: 4.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 74.0ms
Speed: 2.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 64.0ms


tensor([0.8559, 0.3926])
tensor([0.8963])


Speed: 2.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 70.0ms
Speed: 2.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 68.0ms
Speed: 2.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8942])
tensor([0.9059, 0.4531])
tensor([0.8747, 0.6845, 0.3386])


0: 640x384 2 persons, 71.0ms
Speed: 2.0ms preprocess, 71.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 65.0ms
Speed: 2.0ms preprocess, 65.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 68.0ms
Speed: 2.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8589, 0.7309])
tensor([0.8706, 0.7954, 0.3544, 0.3071])
tensor([0.8867, 0.8124, 0.2985, 0.2680])


0: 640x384 3 persons, 67.0ms
Speed: 2.0ms preprocess, 67.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 75.0ms
Speed: 2.0ms preprocess, 75.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 69.0ms


tensor([0.8846, 0.8435, 0.2599])
tensor([0.8838, 0.8820, 0.4599])


Speed: 4.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 99.0ms
Speed: 2.0ms preprocess, 99.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 64.7ms


tensor([0.8498, 0.7191, 0.5325])
tensor([0.8854, 0.8689, 0.5235])


Speed: 2.0ms preprocess, 64.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 75.0ms
Speed: 2.0ms preprocess, 75.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 66.0ms
Speed: 2.0ms preprocess, 66.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9033, 0.8675, 0.3403])
tensor([0.9098, 0.8738, 0.3586])
tensor([0.8789, 0.8785])


0: 640x384 2 persons, 70.0ms
Speed: 2.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 68.0ms
Speed: 2.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 69.0ms
Speed: 3.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.9104, 0.8187])
tensor([0.9052, 0.7457])



0: 640x384 2 persons, 72.0ms
Speed: 2.0ms preprocess, 72.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 68.0ms
Speed: 1.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.9120, 0.6827])
tensor([0.8820, 0.5036])
tensor([0.8975])



0: 640x384 1 person, 76.0ms
Speed: 1.0ms preprocess, 76.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 69.0ms


tensor([0.9186])
tensor([0.9225])


Speed: 3.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 71.0ms
Speed: 2.0ms preprocess, 71.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 69.4ms
Speed: 2.0ms preprocess, 69.4ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8944])
tensor([0.8914, 0.3006])
tensor([0.8532, 0.4030])


0: 640x384 1 person, 95.0ms
Speed: 3.0ms preprocess, 95.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 72.8ms
Speed: 2.0ms preprocess, 72.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 77.0ms


tensor([0.8644])
tensor([0.8895])


Speed: 3.0ms preprocess, 77.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 74.0ms
Speed: 2.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 70.7ms
Speed: 2.0ms preprocess, 70.7ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.6176])
tensor([0.8172, 0.6640, 0.2636])
tensor([0.8543, 0.7711])


0: 640x384 2 persons, 69.0ms
Speed: 2.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 79.0ms
Speed: 2.0ms preprocess, 79.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 2 persons, 73.0ms


tensor([0.8374, 0.8004])
tensor([0.8221, 0.6429, 0.3149, 0.2941])


Speed: 2.0ms preprocess, 73.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 70.0ms
Speed: 2.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 3 persons, 62.0ms
Speed: 1.0ms preprocess, 62.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8702, 0.8286])
tensor([0.8912, 0.7881, 0.5586, 0.2598])
tensor([0.9310, 0.8298, 0.7672])


0: 640x384 3 persons, 61.0ms
Speed: 2.0ms preprocess, 61.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 73.0ms
Speed: 2.0ms preprocess, 73.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 63.2ms
Speed: 3.0ms preprocess, 63.2ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.8939, 0.8350, 0.7315])
tensor([0.9120, 0.9091, 0.8049, 0.4669])
tensor([0.9357, 0.8985, 0.8150, 0.7359])



0: 640x384 4 persons, 87.0ms
Speed: 2.0ms preprocess, 87.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 61.7ms
Speed: 2.0ms preprocess, 61.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 63.0ms
Speed: 2.0ms preprocess, 63.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9323, 0.8883, 0.8274, 0.7605])
tensor([0.9409, 0.9055, 0.8391, 0.8043])
tensor([0.9335, 0.8830, 0.8154, 0.8046])


0: 640x384 4 persons, 67.0ms
Speed: 4.0ms preprocess, 67.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 73.6ms
Speed: 4.0ms preprocess, 73.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 65.0ms
Speed: 2.0ms preprocess, 65.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.8997, 0.8967, 0.7729, 0.7726])
tensor([0.9205, 0.8727, 0.8058, 0.7767])
tensor([0.9201, 0.8724, 0.8208, 0.7868])


0: 640x384 4 persons, 70.7ms
Speed: 3.0ms preprocess, 70.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 68.0ms
Speed: 1.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 63.0ms
Speed: 2.0ms preprocess, 63.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9099, 0.8815, 0.8002, 0.6885])
tensor([0.9001, 0.8592, 0.8007, 0.6995])
tensor([0.9049, 0.8703, 0.7979, 0.6979])


0: 640x384 4 persons, 66.0ms
Speed: 2.0ms preprocess, 66.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 68.0ms
Speed: 1.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 66.0ms


tensor([0.8988, 0.8907, 0.7677, 0.7666])
tensor([0.9059, 0.9052, 0.8025, 0.7783])


Speed: 3.0ms preprocess, 66.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 64.0ms
Speed: 2.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 64.0ms
Speed: 2.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9146, 0.8986, 0.7826, 0.7655])
tensor([0.9313, 0.9178, 0.8640, 0.7877])
tensor([0.9299, 0.9265, 0.8394, 0.8080])


0: 640x384 4 persons, 89.0ms
Speed: 2.0ms preprocess, 89.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 77.0ms
Speed: 2.0ms preprocess, 77.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 70.0ms


tensor([0.9253, 0.8966, 0.8448, 0.7413])
tensor([0.9223, 0.9191, 0.7837, 0.7446, 0.2581])


Speed: 3.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 66.0ms
Speed: 2.0ms preprocess, 66.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 66.0ms
Speed: 2.0ms preprocess, 66.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9242, 0.9194, 0.7919, 0.6575, 0.3172])
tensor([0.9338, 0.9171, 0.7498, 0.6470, 0.3008])
tensor([0.9383, 0.9292, 0.8216, 0.7531])


0: 640x384 4 persons, 70.0ms
Speed: 2.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 73.0ms
Speed: 2.0ms preprocess, 73.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 65.8ms
Speed: 2.0ms preprocess, 65.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9293, 0.9186, 0.8032, 0.7233])
tensor([0.9203, 0.8988, 0.8244, 0.7656])
tensor([0.9219, 0.9069, 0.8124, 0.8073])


0: 640x384 5 persons, 70.0ms
Speed: 2.0ms preprocess, 70.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 74.0ms
Speed: 2.0ms preprocess, 74.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 72.0ms
Speed: 2.0ms preprocess, 72.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9186, 0.8934, 0.8400, 0.7847, 0.3200])
tensor([0.9289, 0.8934, 0.8588, 0.7864, 0.4695])
tensor([0.9289, 0.8965, 0.8657, 0.8088, 0.4327])


0: 640x384 4 persons, 75.0ms
Speed: 2.0ms preprocess, 75.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 77.0ms
Speed: 3.0ms preprocess, 77.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9251, 0.9088, 0.8599, 0.8106])
tensor([0.9313, 0.8892, 0.8416, 0.8166])


0: 640x384 4 persons, 86.0ms
Speed: 2.0ms preprocess, 86.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 76.0ms
Speed: 2.0ms preprocess, 76.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 65.0ms
Speed: 2.0ms preprocess, 65.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9289, 0.8777, 0.8230, 0.8158])
tensor([0.9304, 0.8639, 0.8030, 0.7789])
tensor([0.9225, 0.8203, 0.7618, 0.6333, 0.3249])


0: 640x384 5 persons, 76.0ms
Speed: 2.0ms preprocess, 76.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 5 persons, 77.8ms
Speed: 3.0ms preprocess, 77.8ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 60.0ms
Speed: 2.0ms preprocess, 60.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9239, 0.8674, 0.7585, 0.5305, 0.4674])
tensor([0.9184, 0.8265, 0.8259, 0.6482, 0.3253])
tensor([0.9206, 0.8604, 0.8516, 0.8087])


0: 640x384 4 persons, 67.9ms
Speed: 2.0ms preprocess, 67.9ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 69.0ms
Speed: 4.0ms preprocess, 69.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 66.0ms
Speed: 2.0ms preprocess, 66.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9246, 0.8712, 0.8399, 0.8054])
tensor([0.9296, 0.7938, 0.7816, 0.7518])
tensor([0.9169, 0.8690, 0.7877, 0.7469])


0: 640x384 4 persons, 75.0ms
Speed: 2.0ms preprocess, 75.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 78.0ms
Speed: 2.0ms preprocess, 78.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 66.0ms
Speed: 2.0ms preprocess, 66.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9215, 0.8974, 0.7924, 0.7241])
tensor([0.9191, 0.9152, 0.7801, 0.7641])
tensor([0.9184, 0.9076, 0.8377, 0.7881])


0: 640x384 4 persons, 72.0ms
Speed: 2.0ms preprocess, 72.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 95.0ms
Speed: 2.0ms preprocess, 95.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 64.0ms


tensor([0.9285, 0.9031, 0.7456, 0.6815])
tensor([0.9168, 0.9026, 0.7703, 0.7309])


Speed: 3.0ms preprocess, 64.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 64.0ms
Speed: 2.0ms preprocess, 64.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 4 persons, 60.0ms
Speed: 1.0ms preprocess, 60.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)



tensor([0.9086, 0.9080, 0.7798, 0.7117])
tensor([0.9146, 0.9010, 0.7837, 0.7794])
tensor([0.9141, 0.9006, 0.7975, 0.7651])


0: 640x384 4 persons, 68.0ms
Speed: 2.0ms preprocess, 68.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)


tensor([0.9095, 0.8914, 0.7968, 0.7544])


In [17]:
# image 

img_path = "data/test.png"
#img = cv2.imread(img_path)

# frame = img.read()

results = model(img_path)

# Visualize the results on the frame
annotated_frame = results[0].plot()

# Display the annotated frame
cv2.imshow("YOLOv8 Inference", annotated_frame)

conf = results[0].boxes.conf
print(conf)


image 1/1 c:\Users\haseong\Desktop\eyeTracking\data\test.png: 320x640 6 persons, 72.0ms
Speed: 3.0ms preprocess, 72.0ms inference, 3.0ms postprocess per image at shape (1, 3, 320, 640)


tensor([0.9014, 0.8787, 0.8776, 0.8337, 0.8156, 0.7830])
